version: '3.3'
services:

  frontend:
    image: zukosithlord/foodgram_frontend:latest
    restart: always
    volumes:
      - ../frontend/:/app/result_build/
    container_name: foodgram_frontend

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: zukosithlord/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
    container_name: foodgram_backend

  nginx:
    image: nginx:1.21.3-alpine

    ports:
      - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

      - ../frontend/build:/usr/share/nginx/html/

      - ./docs/:/usr/share/nginx/html/api/docs/

      - static_value:/var/html/static/

      - media_value:/var/html/media/

    depends_on:
      - frontend
      - backend

volumes:
  static_dir:
  media_dir:
  postgres_data:
