# Generated by Django 3.2 on 2023-03-22 16:23

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Список покупок',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[recipes.validators.validate_amount])),
            ],
        ),
        migrations.CreateModel(
            name='Ingridients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('measurement_unit', models.CharField(choices=[('1', 'г.'), ('2', 'мл'), ('3', 'шт'), ('4', 'ст. л.'), ('5', 'по вкусу'), ('6', 'щепотка'), ('7', 'ч. л.'), ('8', 'стакан'), ('9', 'капля'), ('10', 'бутылка'), ('11', 'кг'), ('12', 'лист'), ('13', 'головка'), ('14', 'зубчик'), ('15', 'пучок'), ('16', 'кусок'), ('17', 'кубик'), ('18', 'на глаз'), ('19', 'долька'), ('20', 'веточка'), ('21', 'горсть'), ('22', 'пакет'), ('23', 'банка'), ('24', 'упаковка'), ('25', 'миска'), ('26', 'кружка')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(help_text='Введите название', max_length=150, verbose_name='Название рецепта')),
                ('text', models.TextField(help_text='Введите текст', verbose_name='Текстовое описание')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, upload_to='recipes/', verbose_name='Картинка')),
                ('coocking_duration', models.IntegerField(verbose_name='Время приготовления')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Recipe_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=150, unique=True)),
                ('tag_slug', models.SlugField(unique=True)),
                ('HEX_code', models.CharField(choices=[('#0000FF', 'Синий'), ('#FFA500', 'Оранжевый'), ('#008000', 'Зеленый'), ('#800080', 'Фиолетовый'), ('#FFFF00', 'Желтый')], max_length=10, unique=True)),
            ],
        ),
    ]
