# Generated by Django 3.2 on 2023-05-03 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230503_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='second_name',
        ),
    ]
