# Generated by Django 3.2 on 2023-05-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_ingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Ингридиенты'},
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='measurement',
            new_name='measurement_unit',
        ),
    ]
