# Generated by Django 3.2 on 2023-05-17 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, 'Время готовки не может быть равным 0'), django.core.validators.MaxValueValidator(10080, 'Люди столько не живут')], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(regex='#[A-Fa-f0-9]{6}')], verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(max_length=56, unique=True, validators=[django.core.validators.RegexValidator(regex='[A-Za-z0-9_-]+')], verbose_name='Слаг'),
        ),
    ]
