# Generated by Django 3.2 on 2023-05-19 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_ingredientamount_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0, 'Вы не можете положить 0 чего бы то ни было'), django.core.validators.MaxValueValidator(2147483646, 'Слишком много...')], verbose_name='Количество'),
        ),
    ]
