# Generated by Django 3.2 on 2023-05-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230503_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Test', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(default='Test', max_length=150),
        ),
    ]
